# Setup
title:        Future Fry
tagline:      Lets try !!
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Ranjeet
  url:        https://github.com/ranjeet-floyd

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
